server:
  port: 8080

spring:
  application:
    name: RedisDemo
  redis:
    # 超时时间
    timeout: 20000ms
    # 服务器地址
    host: localhost
    # 服务器端口
    port: 6379
    # 数据库
    database: 0
#    # 密码
#    password: root
    # 配置客户端
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 200
        # 连接池中的最小空闲连接 默认 0
        min-idle: 5
#    lettuce:
#      pool:
#        # 最大连接数，默认为8
#        max-active: 1024
#        # 最大连接阻塞等待时间，默认-1
#        max-wait: -1
#        # 最大空闲连接
#        max-idle: 200
#        # 最小空闲连接
#        min-idle: 5

