server:
  port: 8888

spring:
  # 服务名称
  application:
    name: MysqlDemo
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&useServerPrepStmts=false
    username: root
    password: 123456
    druid:
      # 初始连接数
      initialSize: 0
      # 最大连接数量
      maxActive: 20
      # 最大连接池数量
      maxIdle: 20
      # 最小连接池数量
      minIdle: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000

# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.open.mysql.model
  # 加载全局的配置文件
  config-location: classpath:/mybatis/mybatis-config.xml
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:/mapper/*.xml